import "dotenv/config";
import mongoose from "mongoose";
import { DestinationModel, DestinationRegion, DifficultyLevel, RiskLevel } from "../models/Destination.model";
import { PackageModel, PackageStatus } from "../models/Package.model";
import { UserModel } from "../models/User.model";

const seedData = async (): Promise<void> => {
  try {
    await mongoose.connect(process.env.MONGODB_URI as string);
    console.log("Connected to MongoDB");

    // Get admin user for createdBy
    const admin = await UserModel.findOne({ isSuperAdmin: true });
    if (!admin) {
      console.error("Super Admin not found. Run seed.ts first.");
      process.exit(1);
    }
    const adminId = admin._id;

    // ── Clear existing data ───────────────────────────────
    await DestinationModel.deleteMany({});
    await PackageModel.deleteMany({});
    console.log("Cleared existing destinations and packages");

    // ── 15 Destinations ───────────────────────────────────
    const destinations = await DestinationModel.insertMany([
      {
        name: "Everest Base Camp",
        slug: "everest-base-camp",
        description: "The ultimate trekking destination in Nepal, Everest Base Camp sits at 5364m in the heart of the Khumbu region. Trek through Sherpa villages, ancient monasteries, and breathtaking glaciers to the foot of the world's highest mountain.",
        region: DestinationRegion.HIMALAYA,
        altitude: 5364,
        difficulty: DifficultyLevel.HARD,
        coverImage: "https://images.unsplash.com/photo-1516912481808-3406841bd33c?w=1200",
        images: [
          "https://images.unsplash.com/photo-1533130061792-64b345e4a833?w=800",
          "https://images.unsplash.com/photo-1555164229-7bcd6f480020?w=800",
        ],
        location: { latitude: 27.9881, longitude: 86.9250 },
        seasonalCalendar: [
          { month: "January", status: "avoid" },
          { month: "February", status: "shoulder" },
          { month: "March", status: "best" },
          { month: "April", status: "best" },
          { month: "May", status: "best" },
          { month: "June", status: "avoid" },
          { month: "July", status: "avoid" },
          { month: "August", status: "avoid" },
          { month: "September", status: "shoulder" },
          { month: "October", status: "best" },
          { month: "November", status: "best" },
          { month: "December", status: "avoid" },
        ],
        safetyInfo: {
          riskLevel: RiskLevel.HIGH,
          nearestHospital: "Himalayan Rescue Association, Namche Bazaar",
          emergencyContact: "100",
          rescueService: "Fishtail Air Helicopter",
          timsRequired: true,
          timsCheckpoint: "Lukla / Monjo",
        },
        localTips: [
          "Acclimatize properly — spend 2 nights at Namche Bazaar",
          "Hire a local Sherpa guide for safety and cultural insight",
          "Carry altitude sickness medication (Diamox)",
          "Book teahouses in advance during peak season",
        ],
        bestFor: ["trekking", "mountaineering", "photography", "adventure"],
        isActive: true,
        isFeatured: true,
        createdBy: adminId,
      },
      {
        name: "Annapurna Base Camp",
        slug: "annapurna-base-camp",
        description: "Nestled in the heart of the Annapurna massif at 4130m, ABC offers stunning 360-degree views of Annapurna I, Machapuchare, and Hiunchuli. The trek passes through diverse landscapes from subtropical forests to alpine meadows.",
        region: DestinationRegion.HIMALAYA,
        altitude: 4130,
        difficulty: DifficultyLevel.MODERATE,
        coverImage: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200",
        images: [
          "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800",
        ],
        location: { latitude: 28.5300, longitude: 83.8775 },
        seasonalCalendar: [
          { month: "January", status: "avoid" },
          { month: "February", status: "shoulder" },
          { month: "March", status: "best" },
          { month: "April", status: "best" },
          { month: "May", status: "best" },
          { month: "June", status: "avoid" },
          { month: "July", status: "avoid" },
          { month: "August", status: "avoid" },
          { month: "September", status: "shoulder" },
          { month: "October", status: "best" },
          { month: "November", status: "best" },
          { month: "December", status: "shoulder" },
        ],
        safetyInfo: {
          riskLevel: RiskLevel.MEDIUM,
          nearestHospital: "Gandaki Medical College, Pokhara",
          emergencyContact: "100",
          rescueService: "Air Dynasty Helicopter",
          timsRequired: true,
          timsCheckpoint: "Nayapul",
        },
        localTips: [
          "Start early from Deurali to avoid afternoon clouds at ABC",
          "The rhododendron forests are stunning in March-April",
          "Carry warm layers — temperatures drop significantly at base camp",
        ],
        bestFor: ["trekking", "photography", "adventure", "wildlife"],
        isActive: true,
        isFeatured: true,
        createdBy: adminId,
      },
      {
        name: "Pokhara",
        slug: "pokhara",
        description: "Nepal's adventure capital, Pokhara is famous for its stunning lakeside setting with Phewa Lake reflecting the majestic Annapurna range. A paradise for paragliding, boating, and as the gateway to the Annapurna treks.",
        region: DestinationRegion.POKHARA,
        altitude: 827,
        difficulty: DifficultyLevel.EASY,
        coverImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200",
        images: [
          "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800",
        ],
        location: { latitude: 28.2096, longitude: 83.9856 },
        seasonalCalendar: [
          { month: "January", status: "shoulder" },
          { month: "February", status: "shoulder" },
          { month: "March", status: "best" },
          { month: "April", status: "best" },
          { month: "May", status: "best" },
          { month: "June", status: "avoid" },
          { month: "July", status: "avoid" },
          { month: "August", status: "avoid" },
          { month: "September", status: "shoulder" },
          { month: "October", status: "best" },
          { month: "November", status: "best" },
          { month: "December", status: "shoulder" },
        ],
        safetyInfo: {
          riskLevel: RiskLevel.LOW,
          nearestHospital: "Western Regional Hospital, Pokhara",
          emergencyContact: "100",
          rescueService: "Air Dynasty Helicopter",
          timsRequired: false,
        },
        localTips: [
          "Visit Phewa Lake early morning for best mountain reflections",
          "Try local Thakali food at Lakeside restaurants",
          "Sarangkot sunrise is unmissable — go before 5am",
          "Paragliding is best from October to May",
        ],
        bestFor: ["paragliding", "boating", "trekking", "photography", "cultural"],
        isActive: true,
        isFeatured: true,
        createdBy: adminId,
      },
      {
        name: "Chitwan National Park",
        slug: "chitwan-national-park",
        description: "A UNESCO World Heritage Site, Chitwan is Nepal's premier wildlife sanctuary. Home to one-horned rhinos, Bengal tigers, gharials, and over 500 bird species. Experience jungle safaris, elephant encounters, and tharu cultural shows.",
        region: DestinationRegion.TERAI,
        altitude: 150,
        difficulty: DifficultyLevel.EASY,
        coverImage: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=1200",
        images: [
          "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800",
        ],
        location: { latitude: 27.5291, longitude: 84.3542 },
        seasonalCalendar: [
          { month: "January", status: "best" },
          { month: "February", status: "best" },
          { month: "March", status: "best" },
          { month: "April", status: "best" },
          { month: "May", status: "shoulder" },
          { month: "June", status: "avoid" },
          { month: "July", status: "avoid" },
          { month: "August", status: "avoid" },
          { month: "September", status: "shoulder" },
          { month: "October", status: "best" },
          { month: "November", status: "best" },
          { month: "December", status: "best" },
        ],
        safetyInfo: {
          riskLevel: RiskLevel.MEDIUM,
          nearestHospital: "Bharatpur Hospital, Chitwan",
          emergencyContact: "100",
          rescueService: "National Park Rangers",
          timsRequired: false,
        },
        localTips: [
          "Book jeep safari in advance during peak season",
          "Dawn and dusk are best times for wildlife spotting",
          "Attend the Tharu cultural dance show in the evening",
          "Always stay with your guide in the jungle",
        ],
        bestFor: ["wildlife", "cultural", "photography", "adventure"],
        isActive: true,
        isFeatured: true,
        createdBy: adminId,
      },
      {
        name: "Kathmandu Valley",
        slug: "kathmandu-valley",
        description: "The cultural heart of Nepal, Kathmandu Valley contains seven UNESCO World Heritage Sites including Pashupatinath, Boudhanath, Swayambhunath, and the medieval Durbar Squares. A living museum of art, architecture, and spirituality.",
        region: DestinationRegion.KATHMANDU,
        altitude: 1400,
        difficulty: DifficultyLevel.EASY,
        coverImage: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=1200",
        images: [
          "https://images.unsplash.com/photo-1562462181-b026fe3b481e?w=800",
        ],
        location: { latitude: 27.7172, longitude: 85.3240 },
        seasonalCalendar: [
          { month: "January", status: "shoulder" },
          { month: "February", status: "shoulder" },
          { month: "March", status: "best" },
          { month: "April", status: "best" },
          { month: "May", status: "best" },
          { month: "June", status: "shoulder" },
          { month: "July", status: "avoid" },
          { month: "August", status: "avoid" },
          { month: "September", status: "shoulder" },
          { month: "October", status: "best" },
          { month: "November", status: "best" },
          { month: "December", status: "shoulder" },
        ],
        safetyInfo: {
          riskLevel: RiskLevel.LOW,
          nearestHospital: "Tribhuvan University Teaching Hospital",
          emergencyContact: "100",
          rescueService: "Metropolitan Police",
          timsRequired: false,
        },
        localTips: [
          "Visit Pashupatinath during evening aarti ceremony",
          "Boudhanath is best visited at sunrise",
          "Hire a local guide for Patan Durbar Square",
          "Try momos at New Road restaurants",
        ],
        bestFor: ["cultural", "spiritual", "photography", "culinary"],
        isActive: true,
        isFeatured: false,
        createdBy: adminId,
      },
      {
        name: "Upper Mustang",
        slug: "upper-mustang",
        description: "The forbidden kingdom of Lo, Upper Mustang is a high-altitude desert landscape with ancient cave monasteries, medieval walled cities, and unique Tibetan culture. Only opened to tourists in 1992, it remains one of Nepal's most mystical destinations.",
        region: DestinationRegion.MUSTANG,
        altitude: 3840,
        difficulty: DifficultyLevel.MODERATE,
        coverImage: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1200",
        images: [],
        location: { latitude: 29.1800, longitude: 83.9700 },
        seasonalCalendar: [
          { month: "January", status: "avoid" },
          { month: "February", status: "avoid" },
          { month: "March", status: "shoulder" },
          { month: "April", status: "best" },
          { month: "May", status: "best" },
          { month: "June", status: "best" },
          { month: "July", status: "best" },
          { month: "August", status: "best" },
          { month: "September", status: "best" },
          { month: "October", status: "shoulder" },
          { month: "November", status: "avoid" },
          { month: "December", status: "avoid" },
        ],
        safetyInfo: {
          riskLevel: RiskLevel.MEDIUM,
          nearestHospital: "Jomsom Hospital",
          emergencyContact: "100",
          rescueService: "Tara Air / Mountain Helicopters",
          timsRequired: true,
          timsCheckpoint: "Kagbeni",
        },
        localTips: [
          "Requires special restricted area permit (USD 500/10 days)",
          "Must trek with a registered guide",
          "Lo Manthang walled city is the highlight",
          "Best visited June-September when other trails are monsoon-hit",
        ],
        bestFor: ["trekking", "cultural", "photography", "spiritual", "adventure"],
        isActive: true,
        isFeatured: true,
        createdBy: adminId,
      },
      {
        name: "Rara Lake",
        slug: "rara-lake",
        description: "Nepal's largest lake, Rara sits at 2990m in the remote Mugu district surrounded by pine and juniper forests. The crystal-clear turquoise waters reflect snow-capped peaks in absolute solitude — Nepal's best kept secret.",
        region: DestinationRegion.HIMALAYA,
        altitude: 2990,
        difficulty: DifficultyLevel.MODERATE,
        coverImage: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200",
        images: [],
        location: { latitude: 29.5270, longitude: 82.0877 },
        seasonalCalendar: [
          { month: "January", status: "avoid" },
          { month: "February", status: "avoid" },
          { month: "March", status: "best" },
          { month: "April", status: "best" },
          { month: "May", status: "best" },
          { month: "June", status: "avoid" },
          { month: "July", status: "avoid" },
          { month: "August", status: "avoid" },
          { month: "September", status: "shoulder" },
          { month: "October", status: "best" },
          { month: "November", status: "best" },
          { month: "December", status: "avoid" },
        ],
        safetyInfo: {
          riskLevel: RiskLevel.MEDIUM,
          nearestHospital: "Gamgadhi District Hospital",
          emergencyContact: "100",
          rescueService: "Tara Air",
          timsRequired: true,
          timsCheckpoint: "Jumla",
        },
        localTips: [
          "Fly to Talcha airport — road access is extremely difficult",
          "Very few tourists — book accommodation in advance",
          "Wildlife includes red pandas and Himalayan black bears",
          "No mobile network — inform someone of your itinerary",
        ],
        bestFor: ["trekking", "wildlife", "photography", "adventure"],
        isActive: true,
        isFeatured: false,
        createdBy: adminId,
      },
      {
        name: "Langtang Valley",
        slug: "langtang-valley",
        description: "The closest major trekking destination to Kathmandu, Langtang Valley offers spectacular mountain scenery, Tamang villages, and the famous Kyanjin Gompa at 3870m. Known as the Valley of Glaciers, it's perfect for a week-long trek.",
        region: DestinationRegion.HIMALAYA,
        altitude: 3870,
        difficulty: DifficultyLevel.MODERATE,
        coverImage: "https://images.unsplash.com/photo-1516912481808-3406841bd33c?w=1200",
        images: [],
        location: { latitude: 28.2120, longitude: 85.5160 },
        seasonalCalendar: [
          { month: "January", status: "avoid" },
          { month: "February", status: "shoulder" },
          { month: "March", status: "best" },
          { month: "April", status: "best" },
          { month: "May", status: "best" },
          { month: "June", status: "avoid" },
          { month: "July", status: "avoid" },
          { month: "August", status: "avoid" },
          { month: "September", status: "shoulder" },
          { month: "October", status: "best" },
          { month: "November", status: "best" },
          { month: "December", status: "shoulder" },
        ],
        safetyInfo: {
          riskLevel: RiskLevel.MEDIUM,
          nearestHospital: "Langtang Health Post",
          emergencyContact: "100",
          rescueService: "Air Dynasty Helicopter",
          timsRequired: true,
          timsCheckpoint: "Dhunche",
        },
        localTips: [
          "Kyanjin Ri summit (4773m) offers incredible panoramic views",
          "Try yak cheese made at the local cheese factory",
          "The trail was rebuilt after 2015 earthquake — all facilities restored",
        ],
        bestFor: ["trekking", "photography", "cultural", "adventure"],
        isActive: true,
        isFeatured: false,
        createdBy: adminId,
      },
      {
        name: "Lumbini",
        slug: "lumbini",
        description: "The birthplace of Siddhartha Gautama, the Buddha, Lumbini is one of the holiest Buddhist pilgrimage sites in the world. The sacred garden contains the Maya Devi Temple, Ashoka Pillar, sacred pool, and monasteries from 30+ countries.",
        region: DestinationRegion.TERAI,
        altitude: 100,
        difficulty: DifficultyLevel.EASY,
        coverImage: "https://images.unsplash.com/photo-1562462181-b026fe3b481e?w=1200",
        images: [],
        location: { latitude: 27.4833, longitude: 83.2764 },
        seasonalCalendar: [
          { month: "January", status: "best" },
          { month: "February", status: "best" },
          { month: "March", status: "best" },
          { month: "April", status: "best" },
          { month: "May", status: "shoulder" },
          { month: "June", status: "avoid" },
          { month: "July", status: "avoid" },
          { month: "August", status: "avoid" },
          { month: "September", status: "shoulder" },
          { month: "October", status: "best" },
          { month: "November", status: "best" },
          { month: "December", status: "best" },
        ],
        safetyInfo: {
          riskLevel: RiskLevel.LOW,
          nearestHospital: "Lumbini Zonal Hospital",
          emergencyContact: "100",
          rescueService: "Local Police",
          timsRequired: false,
        },
        localTips: [
          "Rent a bicycle to explore the monastic zone",
          "Visit Maya Devi Temple at sunrise for a peaceful experience",
          "Buddha Jayanti (May) is the most sacred festival time",
          "Stay at least 2 nights to explore all monasteries",
        ],
        bestFor: ["spiritual", "cultural", "photography"],
        isActive: true,
        isFeatured: false,
        createdBy: adminId,
      },
      {
        name: "Poon Hill",
        slug: "poon-hill",
        description: "One of the most popular viewpoints in Nepal, Poon Hill (3210m) offers a sunrise panorama of over 20 Himalayan peaks including Dhaulagiri, Annapurna, and Machhapuchhre. The Ghorepani-Poon Hill trek is perfect for beginners.",
        region: DestinationRegion.HIMALAYA,
        altitude: 3210,
        difficulty: DifficultyLevel.EASY,
        coverImage: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200",
        images: [],
        location: { latitude: 28.4000, longitude: 83.6900 },
        seasonalCalendar: [
          { month: "January", status: "shoulder" },
          { month: "February", status: "best" },
          { month: "March", status: "best" },
          { month: "April", status: "best" },
          { month: "May", status: "shoulder" },
          { month: "June", status: "avoid" },
          { month: "July", status: "avoid" },
          { month: "August", status: "avoid" },
          { month: "September", status: "shoulder" },
          { month: "October", status: "best" },
          { month: "November", status: "best" },
          { month: "December", status: "shoulder" },
        ],
        safetyInfo: {
          riskLevel: RiskLevel.LOW,
          nearestHospital: "Gandaki Medical College, Pokhara",
          emergencyContact: "100",
          rescueService: "Air Dynasty Helicopter",
          timsRequired: true,
          timsCheckpoint: "Nayapul",
        },
        localTips: [
          "Wake up at 4am to reach the viewpoint before sunrise",
          "March-April rhododendron bloom makes the trail magical",
          "The loop via Tadapani and Ghandruk is highly recommended",
        ],
        bestFor: ["trekking", "photography", "adventure"],
        isActive: true,
        isFeatured: false,
        createdBy: adminId,
      },
      {
        name: "Manaslu Circuit",
        slug: "manaslu-circuit",
        description: "The Manaslu Circuit is Nepal's most spectacular off-the-beaten-path trek, circling the world's 8th highest peak (8163m). The trail passes through remote Nubri and Tsum valleys, Tibetan Buddhist villages, and crosses the dramatic Larkya La pass at 5106m.",
        region: DestinationRegion.HIMALAYA,
        altitude: 5106,
        difficulty: DifficultyLevel.HARD,
        coverImage: "https://images.unsplash.com/photo-1533130061792-64b345e4a833?w=1200",
        images: [],
        location: { latitude: 28.5490, longitude: 84.5590 },
        seasonalCalendar: [
          { month: "January", status: "avoid" },
          { month: "February", status: "avoid" },
          { month: "March", status: "best" },
          { month: "April", status: "best" },
          { month: "May", status: "shoulder" },
          { month: "June", status: "avoid" },
          { month: "July", status: "avoid" },
          { month: "August", status: "avoid" },
          { month: "September", status: "shoulder" },
          { month: "October", status: "best" },
          { month: "November", status: "best" },
          { month: "December", status: "avoid" },
        ],
        safetyInfo: {
          riskLevel: RiskLevel.HIGH,
          nearestHospital: "Gorkha Hospital",
          emergencyContact: "100",
          rescueService: "Fishtail Air Helicopter",
          timsRequired: true,
          timsCheckpoint: "Soti Khola",
        },
        localTips: [
          "Requires restricted area permit — only with licensed agency",
          "Larkya La pass crossing should start before 4am",
          "Fewer teahouses than other routes — carry extra snacks",
          "Much less crowded than EBC or Annapurna Circuit",
        ],
        bestFor: ["trekking", "adventure", "photography"],
        isActive: true,
        isFeatured: false,
        createdBy: adminId,
      },
      {
        name: "Gosaikunda",
        slug: "gosaikunda",
        description: "A sacred alpine lake at 4380m, Gosaikunda is one of Nepal's most revered Hindu pilgrimage sites. During Janai Purnima festival, thousands of pilgrims trek to the lake. The route passes through Langtang National Park with stunning mountain views.",
        region: DestinationRegion.HIMALAYA,
        altitude: 4380,
        difficulty: DifficultyLevel.MODERATE,
        coverImage: "https://images.unsplash.com/photo-1516912481808-3406841bd33c?w=1200",
        images: [],
        location: { latitude: 28.0930, longitude: 85.4140 },
        seasonalCalendar: [
          { month: "January", status: "avoid" },
          { month: "February", status: "avoid" },
          { month: "March", status: "best" },
          { month: "April", status: "best" },
          { month: "May", status: "best" },
          { month: "June", status: "shoulder" },
          { month: "July", status: "best" },
          { month: "August", status: "best" },
          { month: "September", status: "shoulder" },
          { month: "October", status: "best" },
          { month: "November", status: "shoulder" },
          { month: "December", status: "avoid" },
        ],
        safetyInfo: {
          riskLevel: RiskLevel.MEDIUM,
          nearestHospital: "Dhunche Health Post",
          emergencyContact: "100",
          rescueService: "Air Dynasty Helicopter",
          timsRequired: true,
          timsCheckpoint: "Dhunche",
        },
        localTips: [
          "Janai Purnima in August draws massive crowds — book early",
          "The lake is frozen December to February",
          "Can be combined with Langtang Valley trek",
        ],
        bestFor: ["spiritual", "trekking", "photography"],
        isActive: true,
        isFeatured: false,
        createdBy: adminId,
      },
      {
        name: "Bhaktapur Durbar Square",
        slug: "bhaktapur-durbar-square",
        description: "The best-preserved medieval city in Nepal, Bhaktapur's Durbar Square is a UNESCO World Heritage Site filled with magnificent temples, courtyards, and traditional Newari architecture. Famous for its 55-window palace, Nyatapola Temple, and Bisket Jatra festival.",
        region: DestinationRegion.KATHMANDU,
        altitude: 1401,
        difficulty: DifficultyLevel.EASY,
        coverImage: "https://images.unsplash.com/photo-1562462181-b026fe3b481e?w=1200",
        images: [],
        location: { latitude: 27.6722, longitude: 85.4298 },
        seasonalCalendar: [
          { month: "January", status: "shoulder" },
          { month: "February", status: "shoulder" },
          { month: "March", status: "best" },
          { month: "April", status: "best" },
          { month: "May", status: "best" },
          { month: "June", status: "shoulder" },
          { month: "July", status: "shoulder" },
          { month: "August", status: "shoulder" },
          { month: "September", status: "shoulder" },
          { month: "October", status: "best" },
          { month: "November", status: "best" },
          { month: "December", status: "shoulder" },
        ],
        safetyInfo: {
          riskLevel: RiskLevel.LOW,
          nearestHospital: "NIST Hospital, Bhaktapur",
          emergencyContact: "100",
          rescueService: "Metropolitan Police",
          timsRequired: false,
        },
        localTips: [
          "Entry fee required — get receipt stamped for multi-day visits",
          "Try Juju Dhau (king curd) — Bhaktapur specialty",
          "Pottery Square is fascinating to watch artisans at work",
          "Bisket Jatra in April is the most spectacular festival",
        ],
        bestFor: ["cultural", "photography", "culinary", "spiritual"],
        isActive: true,
        isFeatured: false,
        createdBy: adminId,
      },
      {
        name: "Kanchenjunga Base Camp",
        slug: "kanchenjunga-base-camp",
        description: "The world's third highest peak (8586m) base camp trek is one of Nepal's most remote and rewarding adventures. The eastern Himalaya trek passes through pristine forests, unspoiled villages, and offers incredible views rarely seen by tourists.",
        region: DestinationRegion.EASTERN,
        altitude: 5143,
        difficulty: DifficultyLevel.EXTREME,
        coverImage: "https://images.unsplash.com/photo-1533130061792-64b345e4a833?w=1200",
        images: [],
        location: { latitude: 27.7025, longitude: 88.1475 },
        seasonalCalendar: [
          { month: "January", status: "avoid" },
          { month: "February", status: "avoid" },
          { month: "March", status: "best" },
          { month: "April", status: "best" },
          { month: "May", status: "best" },
          { month: "June", status: "avoid" },
          { month: "July", status: "avoid" },
          { month: "August", status: "avoid" },
          { month: "September", status: "shoulder" },
          { month: "October", status: "best" },
          { month: "November", status: "shoulder" },
          { month: "December", status: "avoid" },
        ],
        safetyInfo: {
          riskLevel: RiskLevel.EXTREME,
          nearestHospital: "B.P. Koirala Institute, Dharan",
          emergencyContact: "100",
          rescueService: "Simrik Air Helicopter",
          timsRequired: true,
          timsCheckpoint: "Taplejung",
        },
        localTips: [
          "Requires restricted area permit and licensed guide",
          "Minimum 3 weeks needed for the full circuit",
          "Very limited teahouses — camping recommended",
          "Only for experienced trekkers with excellent fitness",
        ],
        bestFor: ["trekking", "adventure", "photography"],
        isActive: true,
        isFeatured: false,
        createdBy: adminId,
      },
      {
        name: "Bandipur",
        slug: "bandipur",
        description: "A perfectly preserved hilltop town that time forgot, Bandipur offers stunning mountain views, traditional Newari culture, and a car-free bazaar frozen in the 18th century. Perfect for a peaceful 2-3 day escape with cave exploration and village walks.",
        region: DestinationRegion.HIMALAYA,
        altitude: 1030,
        difficulty: DifficultyLevel.EASY,
        coverImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200",
        images: [],
        location: { latitude: 27.9340, longitude: 84.4120 },
        seasonalCalendar: [
          { month: "January", status: "shoulder" },
          { month: "February", status: "best" },
          { month: "March", status: "best" },
          { month: "April", status: "best" },
          { month: "May", status: "best" },
          { month: "June", status: "shoulder" },
          { month: "July", status: "avoid" },
          { month: "August", status: "avoid" },
          { month: "September", status: "shoulder" },
          { month: "October", status: "best" },
          { month: "November", status: "best" },
          { month: "December", status: "shoulder" },
        ],
        safetyInfo: {
          riskLevel: RiskLevel.LOW,
          nearestHospital: "Damauli Hospital",
          emergencyContact: "100",
          rescueService: "Local Police",
          timsRequired: false,
        },
        localTips: [
          "No motorized vehicles in the main bazaar — wonderfully peaceful",
          "Siddha Cave is one of the largest caves in South Asia",
          "Sunrise views of Annapurna and Manaslu are spectacular",
          "Try the local Newari cuisine at family-run restaurants",
        ],
        bestFor: ["cultural", "photography", "adventure", "spiritual"],
        isActive: true,
        isFeatured: false,
        createdBy: adminId,
      },
    ]);

    console.log(`✅ Created ${destinations.length} destinations`);

    // Map destination names to IDs for packages
    const destMap: Record<string, mongoose.Types.ObjectId> = {};
    destinations.forEach((d) => { destMap[d.slug] = d._id; });

    // ── 15 Packages ───────────────────────────────────────
    const packages = await PackageModel.insertMany([
      {
        title: "Everest Base Camp Trek — 14 Days",
        slug: "everest-base-camp-trek-14-days",
        description: "The ultimate bucket list adventure — trek to the base of the world's highest mountain through the legendary Khumbu Valley. Experience Sherpa culture, Buddhist monasteries, and breathtaking Himalayan scenery on this classic 14-day expedition.",
        destination: destMap["everest-base-camp"],
        duration: 14,
        groupSize: { min: 2, max: 12 },
        difficulty: DifficultyLevel.HARD,
        price: 85000,
        costBreakdown: { transport: 15000, accommodation: 28000, meals: 14000, guide: 18000, permits: 10000, other: 0 },
        itinerary: [
          { day: 1, title: "Kathmandu — Lukla — Phakding", description: "Fly to Tenzing-Hillary Airport (2860m) and trek to Phakding.", accommodation: "Teahouse", meals: "Dinner" },
          { day: 2, title: "Phakding — Namche Bazaar", description: "Trek through Sagarmatha National Park to the Sherpa capital at 3440m.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 3, title: "Acclimatization Day — Namche", description: "Rest and acclimatize. Optional hike to Everest View Hotel.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 4, title: "Namche — Tengboche", description: "Trek to Tengboche Monastery (3867m) with stunning Ama Dablam views.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 5, title: "Tengboche — Dingboche", description: "Continue through rhododendron forests to Dingboche at 4360m.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 6, title: "Acclimatization — Dingboche", description: "Hike to Nagarjun Hill for panoramic views. Rest day.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 7, title: "Dingboche — Lobuche", description: "Trek across the Khumbu moraine to Lobuche at 4940m.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 8, title: "Lobuche — Gorak Shep — EBC", description: "Trek to Everest Base Camp (5364m)! Return to Gorak Shep.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 9, title: "Gorak Shep — Kala Patthar — Pheriche", description: "Pre-dawn hike to Kala Patthar (5545m) for the best Everest views. Descend to Pheriche.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 10, title: "Pheriche — Namche Bazaar", description: "Long descent back through familiar terrain to Namche.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 11, title: "Namche — Lukla", description: "Final trek back to Lukla.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 12, title: "Lukla — Kathmandu", description: "Fly back to Kathmandu. Celebration dinner.", accommodation: "Hotel", meals: "Breakfast, Dinner" },
          { day: 13, title: "Kathmandu Sightseeing", description: "Visit Boudhanath and Pashupatinath. Free afternoon.", accommodation: "Hotel", meals: "Breakfast" },
          { day: 14, title: "Departure", description: "Transfer to airport for departure.", accommodation: "", meals: "Breakfast" },
        ],
        includes: ["Airport transfers", "Domestic Kathmandu-Lukla-Kathmandu flights", "All teahouse accommodation", "3 meals daily on trek", "Experienced English-speaking guide", "Porter (1 per 2 trekkers)", "Sagarmatha National Park permit", "TIMS card", "First aid kit"],
        excludes: ["International flights", "Nepal visa", "Travel insurance", "Tips for guide and porter", "Personal expenses", "Alcoholic beverages"],
        coverImage: "https://images.unsplash.com/photo-1516912481808-3406841bd33c?w=1200",
        images: ["https://images.unsplash.com/photo-1533130061792-64b345e4a833?w=800"],
        status: PackageStatus.PUBLISHED,
        isFeatured: true,
        isBestSeller: true,
        rating: 4.9,
        reviewCount: 48,
        ecoScore: 4.2,
        createdBy: adminId,
      },
      {
        title: "Annapurna Circuit Trek — 21 Days",
        slug: "annapurna-circuit-trek-21-days",
        description: "One of the world's classic treks, the Annapurna Circuit circumnavigates the entire Annapurna massif crossing the dramatic Thorong La pass at 5416m. Pass through diverse landscapes from subtropical valleys to high-altitude desert.",
        destination: destMap["annapurna-base-camp"],
        duration: 21,
        groupSize: { min: 2, max: 12 },
        difficulty: DifficultyLevel.HARD,
        price: 120000,
        costBreakdown: { transport: 20000, accommodation: 42000, meals: 25000, guide: 22000, permits: 11000, other: 0 },
        itinerary: [
          { day: 1, title: "Kathmandu — Besisahar", description: "Drive to Besisahar, trek start point.", accommodation: "Lodge", meals: "Dinner" },
          { day: 2, title: "Besisahar — Bahundanda", description: "Begin the circuit through rice paddies and waterfalls.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 3, title: "Bahundanda — Chamje", description: "Trek through deep gorges along the Marsyangdi River.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 4, title: "Chamje — Dharapani", description: "Enter the pine forest zone with first views of high peaks.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 5, title: "Dharapani — Chame", description: "Pass through apple orchards to district headquarters Chame.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 6, title: "Chame — Pisang", description: "First views of the Annapurna II and dramatic rock walls.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 7, title: "Pisang — Manang", description: "Trek across open highland plateau to Manang at 3519m.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 8, title: "Acclimatization — Manang", description: "Rest day at Manang. Optional hike to Ice Lake (4620m).", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 9, title: "Manang — Yak Kharka", description: "Gradual ascent through the high altitude zone.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 10, title: "Yak Kharka — Thorong Phedi", description: "Final preparation camp before the pass.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 11, title: "Thorong La Pass — Muktinath", description: "The epic 5416m pass crossing! Descend to sacred Muktinath.", accommodation: "Lodge", meals: "Breakfast, Dinner" },
          { day: 12, title: "Muktinath — Kagbeni — Jomsom", description: "Descend through the Kali Gandaki gorge.", accommodation: "Lodge", meals: "Breakfast, Dinner" },
          { day: 13, title: "Jomsom — Marpha — Tukuche", description: "Trek through the apple capital Marpha.", accommodation: "Lodge", meals: "Breakfast, Dinner" },
          { day: 14, title: "Tukuche — Ghasa", description: "Continue south through the deepest gorge in the world.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 15, title: "Ghasa — Tatopani", description: "Reach Tatopani famous for its hot springs.", accommodation: "Lodge", meals: "Breakfast, Dinner" },
          { day: 16, title: "Tatopani — Ghorepani", description: "Steep climb to Ghorepani through rhododendron forests.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 17, title: "Poon Hill Sunrise — Tadapani", description: "Pre-dawn Poon Hill sunrise then trek to Tadapani.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 18, title: "Tadapani — Ghandruk", description: "Descend to the beautiful Gurung village of Ghandruk.", accommodation: "Lodge", meals: "Breakfast, Dinner" },
          { day: 19, title: "Ghandruk — Nayapul — Pokhara", description: "Final descent and drive to Pokhara.", accommodation: "Hotel", meals: "Breakfast" },
          { day: 20, title: "Pokhara — Kathmandu", description: "Tourist bus or flight to Kathmandu. Celebration dinner.", accommodation: "Hotel", meals: "Breakfast, Dinner" },
          { day: 21, title: "Departure", description: "Transfer to airport.", accommodation: "", meals: "Breakfast" },
        ],
        includes: ["All accommodation", "3 meals daily on trek", "Guide and porter", "ACAP permit", "TIMS card", "Transportation Kathmandu-Besisahar and Pokhara-Kathmandu"],
        excludes: ["International flights", "Nepal visa", "Travel insurance", "Personal expenses", "Tips"],
        coverImage: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200",
        images: [],
        status: PackageStatus.PUBLISHED,
        isFeatured: true,
        isBestSeller: false,
        rating: 4.8,
        reviewCount: 32,
        ecoScore: 4.0,
        createdBy: adminId,
      },
      {
        title: "Pokhara 3-Day Adventure",
        slug: "pokhara-3-day-adventure",
        description: "Experience the best of Pokhara in 3 action-packed days. Paraglide over Phewa Lake, witness sunrise from Sarangkot, explore Devi Falls and Gupteshwor Cave, and hike to the World Peace Stupa.",
        destination: destMap["pokhara"],
        duration: 3,
        groupSize: { min: 1, max: 12 },
        difficulty: DifficultyLevel.EASY,
        price: 12000,
        costBreakdown: { transport: 2500, accommodation: 4500, meals: 2000, guide: 2000, permits: 500, other: 500 },
        itinerary: [
          { day: 1, title: "Arrival + Phewa Lake Boat Ride", description: "Arrive in Pokhara, check in and enjoy a boat ride on Phewa Lake. Evening walk at Lakeside.", accommodation: "Lakeside Hotel", meals: "Dinner" },
          { day: 2, title: "Sarangkot Sunrise + Paragliding", description: "Early morning drive to Sarangkot for sunrise. After breakfast, paragliding flight over the valley. Afternoon visit to Devi Falls and Gupteshwor Cave.", accommodation: "Lakeside Hotel", meals: "Breakfast, Dinner" },
          { day: 3, title: "World Peace Stupa + Departure", description: "Morning hike to World Peace Stupa for panoramic views. Afternoon free for shopping. Transfer to airport.", accommodation: "", meals: "Breakfast" },
        ],
        includes: ["Hotel accommodation (2 nights)", "Breakfast daily", "Paragliding flight", "Boat ride", "Local guide", "All transfers"],
        excludes: ["International flights", "Lunch", "Personal expenses", "Tips"],
        coverImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200",
        images: [],
        status: PackageStatus.PUBLISHED,
        isFeatured: true,
        isBestSeller: false,
        rating: 4.7,
        reviewCount: 28,
        ecoScore: 3.8,
        createdBy: adminId,
      },
      {
        title: "Chitwan Jungle Safari — 4 Days",
        slug: "chitwan-jungle-safari-4-days",
        description: "Immerse yourself in Nepal's wild side with a 4-day jungle safari in Chitwan National Park. Spot one-horned rhinos, Bengal tigers, gharials, and hundreds of bird species. Includes elephant interaction and Tharu cultural program.",
        destination: destMap["chitwan-national-park"],
        duration: 4,
        groupSize: { min: 2, max: 10 },
        difficulty: DifficultyLevel.EASY,
        price: 20000,
        costBreakdown: { transport: 4000, accommodation: 8000, meals: 4000, guide: 3000, permits: 1000, other: 0 },
        itinerary: [
          { day: 1, title: "Arrival + Tharu Village Walk", description: "Drive from Kathmandu/Pokhara. Evening Tharu cultural dance show.", accommodation: "Resort", meals: "Dinner" },
          { day: 2, title: "Jeep Safari + Canoe Ride", description: "Early morning jeep safari for rhino and tiger spotting. Afternoon dugout canoe ride on the Rapti River.", accommodation: "Resort", meals: "Breakfast, Lunch, Dinner" },
          { day: 3, title: "Bird Watching + Elephant Breeding Center", description: "Dawn bird watching walk. Visit elephant breeding center. Evening jungle walk.", accommodation: "Resort", meals: "Breakfast, Lunch, Dinner" },
          { day: 4, title: "Morning Safari + Departure", description: "Final morning safari. Drive back to Kathmandu/Pokhara.", accommodation: "", meals: "Breakfast" },
        ],
        includes: ["Resort accommodation (3 nights)", "All meals", "Jeep safari", "Canoe ride", "Elephant breeding center visit", "All park fees", "Naturalist guide"],
        excludes: ["Transportation to/from Chitwan", "Personal expenses", "Tips", "Alcoholic beverages"],
        coverImage: "https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=1200",
        images: [],
        status: PackageStatus.PUBLISHED,
        isFeatured: false,
        isBestSeller: true,
        rating: 4.6,
        reviewCount: 41,
        ecoScore: 4.5,
        createdBy: adminId,
      },
      {
        title: "Kathmandu Cultural Heritage Tour — 3 Days",
        slug: "kathmandu-cultural-heritage-3-days",
        description: "Explore all 7 UNESCO World Heritage Sites in the Kathmandu Valley in 3 days. Visit Pashupatinath, Boudhanath, Swayambhunath, and the three medieval Durbar Squares of Kathmandu, Patan, and Bhaktapur.",
        destination: destMap["kathmandu-valley"],
        duration: 3,
        groupSize: { min: 1, max: 15 },
        difficulty: DifficultyLevel.EASY,
        price: 15000,
        costBreakdown: { transport: 3000, accommodation: 6000, meals: 3000, guide: 2500, permits: 500, other: 0 },
        itinerary: [
          { day: 1, title: "Kathmandu Durbar Square + Pashupatinath + Boudhanath", description: "Morning at Kathmandu Durbar Square. Afternoon Pashupatinath evening aarti. Evening Boudhanath kora.", accommodation: "Thamel Hotel", meals: "Breakfast, Dinner" },
          { day: 2, title: "Swayambhunath + Patan Durbar Square", description: "Sunrise at Swayambhunath (Monkey Temple). Explore magnificent Patan Durbar Square and Golden Temple.", accommodation: "Thamel Hotel", meals: "Breakfast, Dinner" },
          { day: 3, title: "Bhaktapur + Changu Narayan", description: "Full day in Bhaktapur — Durbar Square, Pottery Square, Taumadhi Square. Visit Changu Narayan temple.", accommodation: "", meals: "Breakfast" },
        ],
        includes: ["Hotel (2 nights)", "Breakfast daily", "Expert cultural guide", "All entry fees", "Private vehicle"],
        excludes: ["Lunch", "Dinner (except day 1)", "Personal shopping", "Tips"],
        coverImage: "https://images.unsplash.com/photo-1562462181-b026fe3b481e?w=1200",
        images: [],
        status: PackageStatus.PUBLISHED,
        isFeatured: false,
        isBestSeller: false,
        rating: 4.5,
        reviewCount: 19,
        ecoScore: 3.5,
        createdBy: adminId,
      },
      {
        title: "Upper Mustang Hidden Kingdom — 10 Days",
        slug: "upper-mustang-hidden-kingdom-10-days",
        description: "Venture into the forbidden kingdom of Lo, one of the last unspoiled Himalayan kingdoms. Trek through a dramatic high-altitude desert landscape to the walled medieval city of Lo Manthang with its ancient cave monasteries and Tibetan culture.",
        destination: destMap["upper-mustang"],
        duration: 10,
        groupSize: { min: 2, max: 10 },
        difficulty: DifficultyLevel.MODERATE,
        price: 95000,
        costBreakdown: { transport: 15000, accommodation: 25000, meals: 20000, guide: 15000, permits: 20000, other: 0 },
        itinerary: [
          { day: 1, title: "Pokhara — Jomsom — Kagbeni", description: "Flight to Jomsom. Trek to Kagbeni, gateway to Upper Mustang.", accommodation: "Lodge", meals: "Dinner" },
          { day: 2, title: "Kagbeni — Chele", description: "Enter the restricted zone. Trek through arid canyon landscapes.", accommodation: "Lodge", meals: "Breakfast, Dinner" },
          { day: 3, title: "Chele — Syangboche", description: "Cross dramatic red cliffs and wind-eroded formations.", accommodation: "Lodge", meals: "Breakfast, Dinner" },
          { day: 4, title: "Syangboche — Ghemi", description: "Visit ancient Ghar Gompa cave monastery.", accommodation: "Lodge", meals: "Breakfast, Dinner" },
          { day: 5, title: "Ghemi — Tsarang", description: "Explore Tsarang fortress and monastery with sky caves.", accommodation: "Lodge", meals: "Breakfast, Dinner" },
          { day: 6, title: "Tsarang — Lo Manthang", description: "Arrive at the walled medieval capital of Lo Kingdom!", accommodation: "Lodge", meals: "Breakfast, Dinner" },
          { day: 7, title: "Lo Manthang Exploration", description: "Full day exploring palaces, monasteries, and the ancient city.", accommodation: "Lodge", meals: "Breakfast, Dinner" },
          { day: 8, title: "Lo Manthang — Charang", description: "Begin return journey via different route.", accommodation: "Lodge", meals: "Breakfast, Dinner" },
          { day: 9, title: "Charang — Kagbeni — Jomsom", description: "Return to Jomsom for flight next morning.", accommodation: "Lodge", meals: "Breakfast, Dinner" },
          { day: 10, title: "Jomsom — Pokhara", description: "Morning flight to Pokhara.", accommodation: "", meals: "Breakfast" },
        ],
        includes: ["All accommodation", "All meals on trek", "Restricted area permit (USD 500)", "Annapurna Conservation permit", "Licensed guide", "Porter", "Jomsom flights"],
        excludes: ["International flights", "Nepal visa", "Travel insurance", "Personal expenses"],
        coverImage: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1200",
        images: [],
        status: PackageStatus.PUBLISHED,
        isFeatured: true,
        isBestSeller: false,
        rating: 4.9,
        reviewCount: 15,
        ecoScore: 4.8,
        createdBy: adminId,
      },
      {
        title: "Annapurna Base Camp Trek — 12 Days",
        slug: "annapurna-base-camp-trek-12-days",
        description: "Trek to the dramatic amphitheater of Annapurna Base Camp (4130m) surrounded by towering Himalayan giants. Pass through the legendary Modi Khola valley, Gurung villages, and stunning rhododendron forests on this unforgettable journey.",
        destination: destMap["annapurna-base-camp"],
        duration: 12,
        groupSize: { min: 2, max: 12 },
        difficulty: DifficultyLevel.MODERATE,
        price: 65000,
        costBreakdown: { transport: 10000, accommodation: 22000, meals: 16000, guide: 12000, permits: 5000, other: 0 },
        itinerary: [
          { day: 1, title: "Pokhara — Tikhedhunga", description: "Drive to Nayapul, trek to Tikhedhunga.", accommodation: "Teahouse", meals: "Dinner" },
          { day: 2, title: "Tikhedhunga — Ghorepani", description: "Climb 3500 stone steps through rhododendron forest to Ghorepani.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 3, title: "Poon Hill Sunrise — Tadapani", description: "Pre-dawn Poon Hill sunrise. Trek to Tadapani.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 4, title: "Tadapani — Chhomrong", description: "Trek to the Gurung village of Chhomrong with great Annapurna views.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 5, title: "Chhomrong — Himalayan Hotel", description: "Descend and re-ascend through bamboo and rhododendron forest.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 6, title: "Himalayan Hotel — Deurali", description: "Enter the sanctuary. Steep climb through the Modi Khola gorge.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 7, title: "Deurali — Annapurna Base Camp", description: "Arrive at ABC! 360° views of Annapurna I, Machapuchare, Hiunchuli.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 8, title: "ABC — Bamboo", description: "Descend with stunning morning views. Trek to Bamboo.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 9, title: "Bamboo — Jhinu Danda", description: "Continue descent to Jhinu for natural hot springs.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 10, title: "Jhinu — Landruk — Tolka", description: "Trek through terraced fields with Annapurna South views.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 11, title: "Tolka — Dhampus — Pokhara", description: "Final descent to Pokhara via scenic Dhampus village.", accommodation: "Hotel", meals: "Breakfast" },
          { day: 12, title: "Departure from Pokhara", description: "Free morning. Bus or flight to Kathmandu.", accommodation: "", meals: "Breakfast" },
        ],
        includes: ["All teahouse accommodation", "3 meals daily on trek", "ACAP permit", "TIMS", "Experienced guide", "Porter", "Transport Pokhara-Nayapul-Pokhara"],
        excludes: ["International flights", "Nepal visa", "Travel insurance", "Personal expenses", "Tips"],
        coverImage: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200",
        images: [],
        status: PackageStatus.PUBLISHED,
        isFeatured: true,
        isBestSeller: false,
        rating: 4.8,
        reviewCount: 36,
        ecoScore: 4.1,
        createdBy: adminId,
      },
      {
        title: "Langtang Valley Trek — 7 Days",
        slug: "langtang-valley-trek-7-days",
        description: "The closest major trek to Kathmandu, Langtang Valley offers stunning glaciers, yak pastures, and Tamang Buddhist culture. Trek to Kyanjin Gompa and climb Kyanjin Ri (4773m) for panoramic views of Langtang Lirung and beyond.",
        destination: destMap["langtang-valley"],
        duration: 7,
        groupSize: { min: 2, max: 12 },
        difficulty: DifficultyLevel.MODERATE,
        price: 35000,
        costBreakdown: { transport: 5000, accommodation: 12000, meals: 8000, guide: 7000, permits: 3000, other: 0 },
        itinerary: [
          { day: 1, title: "Kathmandu — Syabrubesi", description: "Drive 7-8 hours to the trek start point.", accommodation: "Lodge", meals: "Dinner" },
          { day: 2, title: "Syabrubesi — Lama Hotel", description: "Trek through bamboo and oak forest along the Langtang Khola.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 3, title: "Lama Hotel — Langtang Village", description: "Climb through rhododendron forest to the rebuilt Langtang Village.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 4, title: "Langtang — Kyanjin Gompa", description: "Trek across alpine meadows to Kyanjin Gompa. Visit the cheese factory.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 5, title: "Kyanjin Ri Hike", description: "Climb Kyanjin Ri (4773m) for breathtaking panoramic views. Rest afternoon.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 6, title: "Kyanjin — Lama Hotel", description: "Descend back through the valley.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 7, title: "Lama Hotel — Syabrubesi — Kathmandu", description: "Final descent and drive back to Kathmandu.", accommodation: "", meals: "Breakfast" },
        ],
        includes: ["Transport Kathmandu-Syabrubesi-Kathmandu", "All accommodation", "3 meals daily", "Langtang National Park permit", "TIMS", "Guide", "Porter"],
        excludes: ["International flights", "Nepal visa", "Travel insurance", "Personal expenses", "Tips"],
        coverImage: "https://images.unsplash.com/photo-1516912481808-3406841bd33c?w=1200",
        images: [],
        status: PackageStatus.PUBLISHED,
        isFeatured: false,
        isBestSeller: false,
        rating: 4.6,
        reviewCount: 22,
        ecoScore: 4.3,
        createdBy: adminId,
      },
      {
        title: "Poon Hill Trek — 5 Days",
        slug: "poon-hill-trek-5-days",
        description: "The most popular short trek in Nepal, perfect for beginners and families. Trek through Gurung villages, rhododendron forests, and reach the famous Poon Hill viewpoint for a sunrise panorama of 20+ Himalayan peaks.",
        destination: destMap["poon-hill"],
        duration: 5,
        groupSize: { min: 1, max: 15 },
        difficulty: DifficultyLevel.EASY,
        price: 18000,
        costBreakdown: { transport: 3000, accommodation: 7000, meals: 5000, guide: 2500, permits: 500, other: 0 },
        itinerary: [
          { day: 1, title: "Pokhara — Tikhedhunga", description: "Drive to Nayapul, trek to Tikhedhunga (1540m).", accommodation: "Teahouse", meals: "Dinner" },
          { day: 2, title: "Tikhedhunga — Ghorepani", description: "Trek up through rhododendron forest to Ghorepani (2860m).", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 3, title: "Poon Hill Sunrise — Tadapani", description: "Pre-dawn hike to Poon Hill (3210m) for magical sunrise. Trek to Tadapani.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 4, title: "Tadapani — Ghandruk", description: "Descend to the beautiful Gurung village of Ghandruk.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 5, title: "Ghandruk — Nayapul — Pokhara", description: "Final descent and drive back to Pokhara.", accommodation: "", meals: "Breakfast" },
        ],
        includes: ["All teahouse accommodation", "3 meals daily", "ACAP permit", "TIMS", "Guide", "Transport Pokhara-Nayapul-Pokhara"],
        excludes: ["International flights", "Personal expenses", "Tips"],
        coverImage: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200",
        images: [],
        status: PackageStatus.PUBLISHED,
        isFeatured: false,
        isBestSeller: true,
        rating: 4.7,
        reviewCount: 55,
        ecoScore: 4.0,
        createdBy: adminId,
      },
      {
        title: "Lumbini Pilgrimage Tour — 3 Days",
        slug: "lumbini-pilgrimage-tour-3-days",
        description: "A spiritual journey to the birthplace of Lord Buddha. Visit the sacred Maya Devi Temple, Ashoka Pillar, and monasteries from over 30 countries. A deeply moving experience for pilgrims and cultural travelers alike.",
        destination: destMap["lumbini"],
        duration: 3,
        groupSize: { min: 1, max: 20 },
        difficulty: DifficultyLevel.EASY,
        price: 8000,
        costBreakdown: { transport: 2000, accommodation: 3000, meals: 2000, guide: 800, permits: 200, other: 0 },
        itinerary: [
          { day: 1, title: "Kathmandu — Lumbini", description: "Flight or drive to Lumbini. Check in and evening visit to the sacred garden.", accommodation: "Hotel", meals: "Dinner" },
          { day: 2, title: "Sacred Garden + Monastery Zone", description: "Maya Devi Temple, Ashoka Pillar, sacred pond. Afternoon bicycle tour of international monasteries.", accommodation: "Hotel", meals: "Breakfast, Dinner" },
          { day: 3, title: "Tilaurakot + Departure", description: "Visit ancient Tilaurakot — childhood home of Prince Siddhartha. Return journey.", accommodation: "", meals: "Breakfast" },
        ],
        includes: ["Hotel accommodation (2 nights)", "Breakfast daily", "Expert guide", "Bicycle rental", "All entry fees", "Transport within Lumbini"],
        excludes: ["Transport to/from Lumbini", "Lunch", "Personal expenses"],
        coverImage: "https://images.unsplash.com/photo-1562462181-b026fe3b481e?w=1200",
        images: [],
        status: PackageStatus.PUBLISHED,
        isFeatured: false,
        isBestSeller: false,
        rating: 4.5,
        reviewCount: 18,
        ecoScore: 3.9,
        createdBy: adminId,
      },
      {
        title: "Rara Lake Trek — 10 Days",
        slug: "rara-lake-trek-10-days",
        description: "Nepal's best kept secret — a remote trek to the pristine turquoise Rara Lake (2990m), the largest lake in Nepal. Experience absolute solitude, ancient forests, and stunning mountain reflections in one of the world's most untouched landscapes.",
        destination: destMap["rara-lake"],
        duration: 10,
        groupSize: { min: 2, max: 8 },
        difficulty: DifficultyLevel.MODERATE,
        price: 55000,
        costBreakdown: { transport: 12000, accommodation: 18000, meals: 12000, guide: 8000, permits: 5000, other: 0 },
        itinerary: [
          { day: 1, title: "Kathmandu — Nepalgunj", description: "Flight to Nepalgunj. Overnight stay.", accommodation: "Hotel", meals: "Dinner" },
          { day: 2, title: "Nepalgunj — Talcha — Jumla", description: "Mountain flight to Talcha. Trek to Jumla.", accommodation: "Lodge", meals: "Breakfast, Dinner" },
          { day: 3, title: "Jumla — Gothichaur", description: "Trek through pine forests and remote villages.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 4, title: "Gothichaur — Rara Lake", description: "Arrive at the magnificent Rara Lake! First views.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 5, title: "Rara Lake Exploration", description: "Full day to explore the lake shore, forests, and surrounding hills.", accommodation: "Teahouse", meals: "Breakfast, Lunch, Dinner" },
          { day: 6, title: "Rara — Murma Top", description: "Hike to Murma Top (3987m) for panoramic Himalayan views.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 7, title: "Return to Jumla", description: "Begin return trek to Jumla.", accommodation: "Lodge", meals: "Breakfast, Dinner" },
          { day: 8, title: "Jumla Rest Day", description: "Explore Jumla bazaar and local culture.", accommodation: "Lodge", meals: "Breakfast, Dinner" },
          { day: 9, title: "Jumla — Talcha — Nepalgunj", description: "Flight back to Nepalgunj.", accommodation: "Hotel", meals: "Breakfast" },
          { day: 10, title: "Nepalgunj — Kathmandu", description: "Morning flight to Kathmandu.", accommodation: "", meals: "Breakfast" },
        ],
        includes: ["All domestic flights", "All accommodation", "All meals", "Rara National Park permit", "Guide", "Porter"],
        excludes: ["International flights", "Nepal visa", "Travel insurance", "Personal expenses", "Tips"],
        coverImage: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200",
        images: [],
        status: PackageStatus.PUBLISHED,
        isFeatured: false,
        isBestSeller: false,
        rating: 4.8,
        reviewCount: 9,
        ecoScore: 5.0,
        createdBy: adminId,
      },
      {
        title: "Manaslu Circuit Trek — 16 Days",
        slug: "manaslu-circuit-trek-16-days",
        description: "Circle the world's 8th highest mountain on Nepal's most spectacular off-the-beaten-path trek. Cross the dramatic Larkya La pass (5106m) through remote Nubri valleys, ancient monasteries, and pristine wilderness with far fewer trekkers than EBC.",
        destination: destMap["manaslu-circuit"],
        duration: 16,
        groupSize: { min: 2, max: 10 },
        difficulty: DifficultyLevel.HARD,
        price: 110000,
        costBreakdown: { transport: 18000, accommodation: 35000, meals: 25000, guide: 20000, permits: 12000, other: 0 },
        itinerary: [
          { day: 1, title: "Kathmandu — Soti Khola", description: "Drive to Soti Khola, trek start point.", accommodation: "Lodge", meals: "Dinner" },
          { day: 2, title: "Soti Khola — Machhakhola", description: "Trek along the Budhi Gandaki river gorge.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 3, title: "Machhakhola — Jagat", description: "Enter the restricted area. First views of high peaks.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 4, title: "Jagat — Deng", description: "Trek through deep forested gorges.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 5, title: "Deng — Namrung", description: "First views of Manaslu. Traditional villages.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 6, title: "Namrung — Lho", description: "Cross prayer-flag-draped bridges and mani walls.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 7, title: "Lho — Samagaon", description: "Stunning Manaslu views. Visit ancient monastery.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 8, title: "Acclimatization — Samagaon", description: "Rest day with optional hike for acclimatization.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 9, title: "Samagaon — Samdo", description: "High altitude plateau with Tibet border views.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 10, title: "Samdo — Dharamsala", description: "Trek to the base of Larkya La pass.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 11, title: "Larkya La Pass — Bhimthang", description: "Epic pass crossing at 5106m! Descend to Bhimthang.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 12, title: "Bhimthang — Tilje", description: "Long descent through forests.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 13, title: "Tilje — Dharapani", description: "Join the Annapurna Circuit trail.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 14, title: "Dharapani — Besisahar", description: "Final trek day. Drive to Kathmandu.", accommodation: "Hotel", meals: "Breakfast" },
          { day: 15, title: "Kathmandu Sightseeing", description: "Free day in Kathmandu. Celebration dinner.", accommodation: "Hotel", meals: "Breakfast, Dinner" },
          { day: 16, title: "Departure", description: "Transfer to airport.", accommodation: "", meals: "Breakfast" },
        ],
        includes: ["All accommodation", "All meals on trek", "Restricted area permit", "Manaslu Conservation Area permit", "TIMS", "Licensed guide", "Porter", "Transport"],
        excludes: ["International flights", "Nepal visa", "Travel insurance", "Personal expenses", "Tips"],
        coverImage: "https://images.unsplash.com/photo-1533130061792-64b345e4a833?w=1200",
        images: [],
        status: PackageStatus.PUBLISHED,
        isFeatured: false,
        isBestSeller: false,
        rating: 4.9,
        reviewCount: 11,
        ecoScore: 4.7,
        createdBy: adminId,
      },
      {
        title: "Bhaktapur & Patan Day Tour",
        slug: "bhaktapur-patan-day-tour",
        description: "A deep dive into Nepal's medieval heritage on a full day tour of Bhaktapur and Patan, two of the finest examples of Newari architecture in Asia. Explore ancient Durbar Squares, hidden temples, living Buddhist monasteries, and try authentic local cuisine.",
        destination: destMap["bhaktapur-durbar-square"],
        duration: 1,
        groupSize: { min: 1, max: 20 },
        difficulty: DifficultyLevel.EASY,
        price: 3500,
        costBreakdown: { transport: 1000, accommodation: 0, meals: 1000, guide: 1000, permits: 500, other: 0 },
        itinerary: [
          { day: 1, title: "Bhaktapur + Patan Full Day", description: "Morning at Bhaktapur Durbar Square — 55-window palace, Nyatapola Temple, Pottery Square. Lunch at local restaurant. Afternoon Patan — Durbar Square, Golden Temple, Mahabouddha Temple. Return to Kathmandu.", accommodation: "", meals: "Lunch" },
        ],
        includes: ["Private vehicle", "Expert guide", "All entry fees", "Lunch", "Juju Dhau (king curd) tasting"],
        excludes: ["Hotel pickup/dropoff outside Kathmandu", "Personal shopping", "Tips"],
        coverImage: "https://images.unsplash.com/photo-1562462181-b026fe3b481e?w=1200",
        images: [],
        status: PackageStatus.PUBLISHED,
        isFeatured: false,
        isBestSeller: false,
        rating: 4.6,
        reviewCount: 34,
        ecoScore: 3.5,
        createdBy: adminId,
      },
      {
        title: "Gosaikunda Lake Trek — 6 Days",
        slug: "gosaikunda-lake-trek-6-days",
        description: "A sacred high-altitude pilgrimage to Gosaikunda Lake (4380m) in Langtang National Park. Combine stunning mountain scenery with deep Hindu and Buddhist spirituality. Trek through Shivapuri, Helambu, and cross the dramatic Lauribina Pass.",
        destination: destMap["gosaikunda"],
        duration: 6,
        groupSize: { min: 2, max: 12 },
        difficulty: DifficultyLevel.MODERATE,
        price: 28000,
        costBreakdown: { transport: 4000, accommodation: 10000, meals: 7000, guide: 5000, permits: 2000, other: 0 },
        itinerary: [
          { day: 1, title: "Kathmandu — Sundarijal", description: "Drive to Sundarijal, begin trek through Shivapuri National Park.", accommodation: "Teahouse", meals: "Dinner" },
          { day: 2, title: "Sundarijal — Kutumsang", description: "Trek through pine forest and Tamang villages.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 3, title: "Kutumsang — Tharepati", description: "Alpine meadows and first Himalayan views.", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 4, title: "Tharepati — Gosaikunda", description: "Cross Lauribina Pass and descend to the sacred lake!", accommodation: "Teahouse", meals: "Breakfast, Dinner" },
          { day: 5, title: "Gosaikunda — Dhunche", description: "Descend through rhododendron forest to Dhunche.", accommodation: "Lodge", meals: "Breakfast, Dinner" },
          { day: 6, title: "Dhunche — Kathmandu", description: "Drive back to Kathmandu.", accommodation: "", meals: "Breakfast" },
        ],
        includes: ["Transport", "All accommodation", "All meals", "Langtang National Park permit", "TIMS", "Guide"],
        excludes: ["International flights", "Nepal visa", "Personal expenses", "Tips"],
        coverImage: "https://images.unsplash.com/photo-1516912481808-3406841bd33c?w=1200",
        images: [],
        status: PackageStatus.PUBLISHED,
        isFeatured: false,
        isBestSeller: false,
        rating: 4.7,
        reviewCount: 14,
        ecoScore: 4.4,
        createdBy: adminId,
      },
      {
        title: "Bandipur & Pokhara Escape — 5 Days",
        slug: "bandipur-pokhara-escape-5-days",
        description: "Combine the serene hilltop town of Bandipur with the adventure capital Pokhara on this perfect Nepal escape. Explore ancient Newari culture, explore Siddha Cave, then paraglide over Phewa Lake with Annapurna as your backdrop.",
        destination: destMap["bandipur"],
        duration: 5,
        groupSize: { min: 2, max: 12 },
        difficulty: DifficultyLevel.EASY,
        price: 22000,
        costBreakdown: { transport: 5000, accommodation: 9000, meals: 5000, guide: 2000, permits: 500, other: 500 },
        itinerary: [
          { day: 1, title: "Kathmandu — Bandipur", description: "Drive to Bandipur. Explore the car-free Newari bazaar.", accommodation: "Heritage Hotel", meals: "Dinner" },
          { day: 2, title: "Bandipur Exploration", description: "Siddha Cave, sunrise viewpoint, village walk, cultural interactions.", accommodation: "Heritage Hotel", meals: "Breakfast, Dinner" },
          { day: 3, title: "Bandipur — Pokhara", description: "Drive to Pokhara. Afternoon boat ride on Phewa Lake.", accommodation: "Lakeside Hotel", meals: "Breakfast, Dinner" },
          { day: 4, title: "Pokhara Adventures", description: "Morning paragliding. Afternoon visit to Devi Falls and World Peace Stupa.", accommodation: "Lakeside Hotel", meals: "Breakfast, Dinner" },
          { day: 5, title: "Sarangkot Sunrise + Departure", description: "Sunrise at Sarangkot. Drive/flight to Kathmandu.", accommodation: "", meals: "Breakfast" },
        ],
        includes: ["All accommodation", "Daily breakfast and dinner", "Paragliding", "Boat ride", "Guide", "Transport throughout"],
        excludes: ["International flights", "Lunch", "Personal expenses", "Tips"],
        coverImage: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200",
        images: [],
        status: PackageStatus.PUBLISHED,
        isFeatured: false,
        isBestSeller: false,
        rating: 4.6,
        reviewCount: 21,
        ecoScore: 3.7,
        createdBy: adminId,
      },
    ]);

    console.log(`✅ Created ${packages.length} packages`);
    console.log("\n🎉 Data seed completed successfully!");
    console.log(`   Destinations : ${destinations.length}`);
    console.log(`   Packages     : ${packages.length}`);

  } catch (error) {
    console.error("Seed failed:", error);
  } finally {
    await mongoose.disconnect();
    process.exit(0);
  }
};

seedData();